- .coveragerc
- .travis.yml
- README.rst
Some minor corrections to project configuration. Separate test case for 'flake8'.
> CI configuration

- .travis.yml
- bluesky_queueserver/manager.py
- bluesky_queueserver/qserver_cli.py
- requirements.txt
That was easier than I expected.
Still need to add checking on start up if there is a plan in `running_plan` and parameterize this at all...
> move queue to redis

- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/worker.py
- requirements.txt
Add the ability to pass a kafka topic / server through the cli.
> ENH/WIP: start to thread configuration through

- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/test_comms.py
- bluesky_queueserver/manager/worker.py
Also fixed something that I broke while merging the previous PR.
> Some more tests (for 'comms.py')

- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_comms.py
It's to address my comments (https://github.com/bluesky/bluesky-queueserver/pull/40#pullrequestreview-492600380) to the late review :-)
> Folow up on #40

- .gitignore
- .travis.yml
- bluesky_queueserver/server/tests/test_http_server.py
- requirements-dev.txt
This PR covers all currently existing aiohttp routes/endpoints.
> Add http server tests

- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_general.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/server/tests/test_http_server.py
The code for RE Manager and RE Worker are rewritten to use JSON RPC protocol for communication. The code may need improvement in terms of readability and error handling. Most of the handlers are modified to initiate requested action and return instant response. Additional APIs are needed to poll the state of RE Manager to determine if the requested action is completed.
Tests are modified to work with the new version of RE Manager. Some of the modifications are temporary: those tests should be changed when additional APIs are available.
> JSON RPC between RE Manager and RE Worker

- .github/workflows/black.yml
This PR adds the Black Github action.
I applied `black .` manually to fix the rest of the files.
> Black Github action

- .travis.yml
This is mostly a "cosmetic" PR, but I don't think the following line ever worked as the variable wasn't expanded:
```bash
if [ BUILD_DOCS == 'true' ]; then
```
> CI: minor tweaks to .travis.yml file

- .github/workflows/deploy_docs.sh
- .github/workflows/docs_publish.yml
- docs/source/index.rst
Script that publishes documents to `gh-pages` without using third party scripts.
> Doc publishing

- .github/workflows/testing.yml
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/_common.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
The PR contains a number of small tweaks that make execution of unit tests more reliable.
> CI: reliability of unit tests

- README.rst
Update `README.rst` to reflect latest changes. The changes include:
- Plan queue items are referenced as `items` instead of `plans` wherever appropriate.
- Included example for inserting `queue_stop` instruction to the plan queue.
- Document structure was improved.
> DOC: update README.rst

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
This PR contains minor changes to RE Manager code that enable saving a list of Run UIDs in plan history. The example below demonstrates the contents of updated plan history after execution of two identical single-run plans. Each history item now contains a field named `result`, which is used to keep `exit_status` and `run_uids`. Note, that `run_uids` is a list that may contain multiple UIDs in case of multirun plans. Internally, the list of Run UID is Run Engine after completion of a plan.
**Minor API change:** `exit_status` was moved to `result` dictionary.
```
[{'args': [['det1', 'det2']],
'item_type': 'plan',
'item_uid': '665f1af0-97e8-49c4-af10-a20f4b90ddff',
'kwargs': {'delay': 1, 'num': 10},
'name': 'count',
'result': {'exit_status': 'completed',
'run_uids': …
```
> ENH: include UIDs of completed runs in plan execution results in plan history

- bluesky_queueserver/manager/manager.py
Added more detailed INFO log message for operations of starting a plan (prints plan parameters), executing queue instruction (prints instruction parameters). Also added brief INFO messages for indicating the results of execution of `queue_item_add`, `queue_item_add_batch` and `queue_item_update` API requests.
Addresses issue https://github.com/bluesky/bluesky-queueserver/issues/141
> More detailed INFO log messages

- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/profile_collection_sim/99-custom.py
- bluesky_queueserver/server/server.py
Changes:
- Minor fix in the `move_then_count` simulated plan. 
- Added logging message to HTTP server code.
> FIX: Minor fix to a simulated plan in the simulated profile collection

- bluesky_queueserver/__init__.py
- bluesky_queueserver/manager/output_streaming.py
- bluesky_queueserver/manager/tests/test_output_streaming.py
- docs/source/features_and_config.rst
- docs/source/interacting_with_qs.rst
Async version of ``ReceiveConsoleOutput`` class
> Async API for receiving published message with RE Manager console output

- .github/workflows/python-publish.yml
- docs/source/release_history.rst
- Release notes for v0.0.6.
- Add workflow for publishing releases to PyPI.
> Release notes: v0.0.6

- bluesky_queueserver/manager/annotation_decorator.py
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- docs/source/installation.rst
- docs/source/re_manager_api.rst
Hi Dmitri,
For your consideration, I have a pull request that changes the behaviour of the queueserver around (deferred) pausing the RE Worker, 
Please see the commit comment for the details,
> Stop queue on unresolved pause

- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
Timestamps that define time of starting (`time_start`) and stopping or completion (`time_stop`) of plan execution to plan history.
The timestamps could be found in `item[result]` dictionary. Timestamps are floating point numbers returned by `time.time()`. Time of  starting and stopping of individual runs may be found in Data Broker using run UIDs from the list.
Addresses the issue https://github.com/bluesky/bluesky-queueserver/issues/225
- Timestamps `time_start` and `time_stop` are now added to `result` dictionary of each item in plan history.
Unit tests are modified to check new functionality.
> Add timestamps to history items

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/profile_tools.py
- bluesky_queueserver/manager/worker.py
Changes in this PR:
- RE Worker code was refactored to make it easier to understand and modify.
- Foreground tasks (started using `script_upload` and `function_execute` API) are now executed in the main thread of RE Worker. This should not affect execution of tasks except some rare edge cases.
- Foreground tasks (started using `script_upload` and `function_execute` API) are now executed in the main thread of RE Worker.
> Refactor RE Worker code

- .github/workflows/docs_publish.yml
Fetch tags so that the correct version number is displayed on documentation page.
> CI: Fetch tags so that the correct version number is displayed in documentation

- .github/workflows/testing.yml
- bluesky_queueserver/manager/profile_ops.py
- docs/source/installation.rst
- pyproject.toml
We already use Python 3.10, but we don't yet test against it.
> test against Python 3.10

- bluesky_queueserver/manager/tests/test_qserver_cli.py
- docs/source/cli_tools.rst
- docs/source/using_queue_server.rst
Tests and documentation for CLI options for enabling/disabling autostart. Includes the items missed in PR https://github.com/bluesky/bluesky-queueserver/pull/269
> Tests and docs for CLI autostart options.

- docs/source/manager_config.rst
- docs/source/using_queue_server.rst
Changes:
- Fixed a number of mistakes in documentation on RE Manager configuration for IPython mode
- Documentation on `worker` section of the config file.
> More documentation on IPython mode

- .pre-commit-config.yaml
- bluesky_queueserver/manager/tests/test_conversions.py
- docs/source/contributing.rst
- docs/source/index.rst
- docs/source/installation.rst
Added notes for developers to the documentation: installation of development environment, pre-commit,
running tests (with disabled and enabled IPython mode), using `pytest-split`. The notes reflect current configuration
of the project and may be useful for potential contributors.
Also fixed minor `flake8` issue in tests.
> Documentation: instructions for developers

- bluesky_queueserver/manager/profile_ops.py
Improved handling of types by parameter validation algorithm:
- Types like `collections.abc.Iterable` and `collections.abc.Mapping` can be properly handled. The `Iterable` type should not be used for a list of detectors, since a single string is also recognized as iterable type, which is wrong. Use types like `typing.Union[list[bluesky.protocols.Readable], tuple[bluesky.protocols.Readable]]` instead.
- Types defined in `bluesky` package may be used in definitions of callable types, for example:
```
from collections.abc import Callable, Generator
from bluesky.util import Msg
from bluesky.protocols import Readable
def plan(per_shot: Callable[[list[Readable]], Generator[Msg]]):
...
```
Note, that description for `per_shot` parameter in this example will simply have ``__CALLABLE__`` type, but …
> Small improvements of plan parameter validation

- .github/workflows/testing.yml
> CI: add python 3.12 to the test matrix
