bluesky/bluesky-queueserver

- .travis.yml
- README.rst
- bluesky_queueserver/server.py
- bluesky_queueserver/worker.py
This is the proof-of-principle prototype of the QueueServer that implements the following functions:
- management of the queue (add element, remove (pop) last (not first) element, get queue info, read queue);
- creation and initialization, and closing (destruction) of the execution environment (worker process) for Bluesky Run Engine;
- execution of the queue; additional plans may be added while the queue is running executed,
- pausing (immediate and deferred) of running plan (and the queue), resuming, aborting, stopping and halting of the paused plan. If the plan is resumed, execution of the queue is resumed (next plan will be executed once the current plan is completed). If the plan is aborted, stopped or halted, execution of the queue is stopped and the current plan remains in the …
> Proof-of-Principle Prototype of the QueueServer that Manages and Executes the Queue via REST API

- README.rst
- bluesky_queueserver/worker.py
Small improvement in the code: pausing a plan using `RE.request_pause()` instead of generating `SIGINT`. To test the operation the following code may be changes:
Start the server:
```
python -m aiohttp.web -H 0.0.0.0 -P 8080 bluesky_queueserver.server:init_func
```
In a different terminal load a plan (runs for 10 seconds):
```
http POST 0.0.0.0:8080/add_to_queue plan:='{"name":"count", "args":[["det1", "det2"]], "kwargs":{"num":10, "delay":1}}' 
```
Create the environment and start the queue execution (the queue contains one plan):
```
http POST 0.0.0.0:8080/create_environment
http POST 0.0.0.0:8080/process_queue
```
Pause the plan while it is running:
```
http POST 0.0.0.0:8080/re_pause option="immediate"
```
Resume the plan:
```
http POST 0.0.0.0:8080/re_continue option="resume"
``` …
> ENH: pause plan using 'RE.request_pause()' instead of SIGINT

- README.rst
- bluesky_queueserver/manager.py
- bluesky_queueserver/qserver_cli.py
- bluesky_queueserver/server.py
- bluesky_queueserver/worker.py
- setup.py
Simple CLI tool for communicating with RE Manager. RE Manager can be fully controlled by the CLI tool without starting the Web Server. CLI tool may be used in the request-report mode or in monitoring mode. In monitoring mode a 'ping' request is sent to RE Manager periodically. Currently only the number of elements in the queue is returned in response to the 'ping' command. If RE Manager is stopped while monitor is running, the monitor will try to make periodic requests to the manager and report communication errors until the manager is started again.
The PR is based on the code from PR https://github.com/bluesky/bluesky-queueserver/pull/31.
> Simple CLI tool for communicating with RE Manager

- README.rst
- bluesky_queueserver/manager.py
- bluesky_queueserver/server.py
- bluesky_queueserver/worker.py
The Server is split into Web Server and RE Manager. Web Server and RE Manager are executed as separate applications. Communication between Web Server and RE Manager is performed using ZeroMQ. RE Manager is acting as ZeroMQ server, which is responding to requests from the Web Server. In current demo, Web Server is forwarding REST API requests to RE Manager and forwarding the responses back to HTTP client (run in shell).
> Split 'server' module into Web Server and RE Manager

- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/test_general.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/tests/test_examples.py
- requirements.txt
Changes in this PR:
- Switched to `json-rpc` for communication between RE manager and Watchdog.
- Implemented communication timeout and simplistic handling of the timeout exception. 
- Added test case that involves restart of RE Manager while the plan is running.
- Implemented changes in code style based on requests for the previous PR (e.g. proper formatting of logging messages for better efficiency).
> Use `json-rpc` package for communication between RE Manager and Watchdog

- .travis.yml
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/test_comms.py
- bluesky_queueserver/manager/tests/test_start_manager.py
- bluesky_queueserver/tests/common.py
Some more tests. Covered functionality of Watchdog module. Changed `WatchdogProcess.__init__ ()` so that it now accepts classes for RE Manager and RE Worker as parameters. It makes the design modular (any custom classes can be passed as parameters). This also makes testing much easier, since classes that emulate RE Manager and RE Worker APIs and run in threads may be used instead of the real ones that run as separate processes.  
The PR should be safe to merge.
> Testing for Watchdog module

- .travis.yml
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/test_general.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/profile_collection_sim/00-ophyd.py
- bluesky_queueserver/profile_collection_sim/15-plans.py
- bluesky_queueserver/profile_collection_sim/99-custom.py
- setup.py
Simulated beamline profiles are loaded from the directory specified with command-line option `-p` (use `-h`) to see all available options. If the option is not specified, then the 'default' profile collection is loaded. The 'default' profile collection loads all standard simulated Ophyd devices and standard Bluesky plans and intended to be used for testing and evaluation. Parsing of plans is performed from the namespace that contains the loaded devices and plans. The parser is also rewritten for better flexibility. 
Parsing is still performed before the plan is executed. In case a plan can not be parsed, the plan is substituted for a function that will raise exception in the same thread that is supposed to execute the plan. The error message is used to generate the report sent to the …
> Loading of simulated beamline profiles.

- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/test_comms.py
Implementation of basic async client that sends messages and processes responses using 'json-rpc' package. The features include timeout and basic handling of `json-rpc` errors. The functionality of the client is covered by unit tests.
The client is currently used for communication between RE Manager and Watchdog modules on the side of RE Manager. One of the next steps will be to convert communication between RE Manager and RE Worker to `json-rpc` using this client.
> Basic client for async communication using 'json-rpc' package.

- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/conftest.py
- bluesky_queueserver/server/tests/test_http_server.py
- requirements.txt
Summary:
--------------
- Converted all `aiohttp` calls to `fastapi` with corresponding `get`/`post` decorators. That resulted in getting rid of most handler methods from the `WebServer` class, so I use the latter for the ZMQ communications only (the code for those handler methods is commented out for now, but will eventually be removed).
- Used enum validations for `re_pause`/`re_continue` operations.
- Moved the test fixtures for the server into the corresponding `conftest.py` module.
- All tests passed with the existing tests (just with a different web-server fixture, but the same REST API calls).
- Parametrized ZMQ server/port.
**Note**: we have to install `uvicorn` explicitly, or I opted to use `fastapi[all]` which has that dependency.
> FastAPI web server

- README.rst
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_general.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/conftest.py
- bluesky_queueserver/server/tests/test_http_server.py
- requirements.txt
Changes:
- Extended the information returned by 'ping' request. The returned state contains data sufficient to determine if current operation is completed. More convenient APIs may be implemented in the future for waiting for completion of specific operations.
- Changed variable that keeps current state of RE Manager process from string to `super_state_machine.machines.StateMachine` (same as in Bluesky). Currently it is used as enhanced enum (ensures that assigned values are from a fixed set and reduces the chance of an error), but may eventually be used as a state machine when the rest of the code is ready.
- Modified the CLI tests so they are working without artificial delays. The delays are replaced with polling RE Manager state.
- Renamed command/value to method/params in ZMQ-related …
> API for more accurate monitoring of RE Manager state

- README.rst
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/conftest.py
- requirements-dev.txt
- requirements.txt
After discussion in Teams with @cryos and @tacaswell we decided it's safer to switch to `localhost:8080` from a less-restricted `0.0.0.0:8080` (which is a default address/port for formerly used `aiohttp` library).
Also, less dependencies for production - we need `fastapi` and `uvicorn`, but `fastapi[all]` can be installed for dev purposes.
> Fix web-server address/port (0.0.0.0:8080 -> localhost:8080)

- README.rst
- requirements.txt
The server needs redis installed to run, and matplotlib is required for
the best effort callback currently used to output debug information.
There is a msgpack minimum version of 1.0 for bluesky kafka that the
version specifications fixes in default installs.
> Expand installation instructions and requirements

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_general.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/test_http_server.py
Changes to RE Manager API:
- renamed `queue_view` to `get_queue`. It now returns a dictionary with two keys: `queue` - list of plans in the queue (represented as dictionaries, first element in the list is the first plan to run), `running_plan` - dictionary that represents currently running plan (running plan is not part of the queue, `{}` is returned if no plan is currently executed).
- `clear_queue` entry point to HTTP server (the operation was available via CLI client). The test is also added.
- `get_history` and `clear_history` API (both CLI and HTTP). The tests are added.
> Expansion of RE Manager API

- README.rst
- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/test_http_server.py
Changes include:
- Support for loading of 'realistic' beamline profile collections that are using `configure_base` function from `nslsii` package. Files from profile collections are patched by replacing `get_ipython()` function with custom function that returns an object with attribute `user_ns` which holds a reference to `locals()` for the patched file. Patched files are saved as temporary files and loaded by using `runpy`. The original files remain unchanged.
- Additional patching of the files in order to capture traceback in case of exception raised while executing the profile collection.
- `temp` databroker can not be used to accumulated data from RE Worker environment. Probably an option of configuring MongoDB-base databroker should be implemented. The command `print_db_uids` is …
> Load 'Realistic' Beamline Profile Collections into RE Worker environment.

- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
Added support for relative imports in loaded beamline profiles: path to original location of beamline profile collection is added to `sys.path` before startup files are patched and loaded from a temporary directory. Unit tests are added.
> Support for local imports in loaded beamline profiles

- README.rst
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/conftest.py
Changed port number for FastAPI server from 8080 to 60610 in documentation, docstrings and tests.
> Changed default port number for the server from 8080 to 60610

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/_common.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/tests/test_http_server.py
Set up framework for direct testing of RE Manager ZMQ API. To this point API were tested indirectly by either calling `qserver` CLI or using REST API. From this point it is likely that CLI commands and REST APIs will start diverging from ZMQ API used for internal communication between the server and RE manager, so it would be beneficial to separate the tests as well. 
Only a few tests are added so far. There are also some minor changes to the code (mostly error messages).
> Separate tests for RE Manager ZMQ API (only a few tests for now).

- .travis.yml
- README.rst
- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/_common.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/server.py
Contributions: 
- Moved all ZMQ client code to `comms.py`. Class `ZMQCommSendAsync` is used by the web server and function `zmq_single_request` (useful for episodic requests to RE Manager) is used by the CLI tool and unit tests. The API may also be used by third party software if needed.
- Fixed an issue in `server.py` (potentially two event loops).
> ZMQ client API

- .github/workflows/deploy_docs.sh
Changes in this PR allow build to fail in case of collision, which can happen if several builds attempt to push changes to `gh_pages` branch simultaneously. Such event is extremely unlikely if the script `deploy_docs` is used as intended since it requires multiple PRs being merged simultaneously. The change includes replacement of `push --force-with-lease` by `push`. 
Additional changes to the script include multiple `echo` statements helpful for easier navigation in the script output.
> CI: allow build to fail while deploying documentation in case of collision

- bluesky_queueserver/manager/comms.py
Fixed minor bug that prevented the code from running correctly with `pyzmq` v. 20.0.0. In the new version of `pyzmq` the return value of `socket.connect()` is different from `None`. The code was incorrectly using the return value of `socket.connect()` to verify if the connection was established successfully. The changed code does not use the return value of `socket.connect()`.
> FIX: compatibility with pyzmq v20.0.0.

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/tests/test_http_server.py
Make use of the RE Manager MState enum to indicate when the
manager is already underway in the creation or closing of a
RE Worker environment.
Previously the manager would get into a locked up state if
a request to create an environment was received while it was
already mid-way through the act of creating an environment.
> FIX: reject create/close environment requests if already underway (2nd attempt)

- bluesky_queueserver/manager/worker.py
Fixes the issue discovered during testing of the QueueServer. In the default mode, QueueServer is removing references to Run Engine (`RE`) and Data Broker (`db`) from RE namespace and generates a new instance of Run Engine. If the name of configuration file is provided as the value of one of CLI parameters (e.g. `start-re-manager --databroker_config "bmm"`), then a new instance of `db` is created and Run Engine is subscribed to it. A simple modification to the code in this PR includes the reference to `db` into RE namespaces so that it becomes accessible from the executed plans.
> ENH: load reference to 'db' into RE namespace

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/tests/test_http_server.py
The code that implements an option to add `queue_stop` instructions to the plan queue. Once the instruction is encountered during plan execution, the queue execution is stopped. Execution may be resumed by sending `queue_start` request to the manager. The instructions are treated similarly to plans: they can be added to the queue, removed from the queue or moved within the queue. Instructions are assigned `plan_uid` and can be accessed by position and UID (the same way as plans).
Currently an instruction can be added to the queue by sending
```
"instruction": {"action": "queue_stop"}
```
instead of `"plan": {...}` as an argument of `queue_plan_add`. The option of adding instructions is not yet implemented in CLI tool.
The option of adding instructions to the queue makes current naming …
> ENH: implementation of an option to add 'queue_stop' instructions to the plan queue

- README.rst
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/_common.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/conftest.py
- bluesky_queueserver/server/tests/test_http_server.py
The changes in this PR include renaming of a number of API (both 0MQ and REST) to reflect the expansion of functionality of the plan queue. Since the plan queue may now include instructions (currently only instructions that stops execution of the queue is implemented), it is more consistent to name queue items as 'items', not as 'plans'. The PR includes only trivial changes: there are no changes to functionality of the Queue Server.
**NOTE**: In existing installation of QueueServer, history may contain 'old' items that have `plan_uid` instead of `item_uid`. Clear history by running `qserver -c history_clear` to clear the history to ensure consistency of data returned by `/history/get` API.
The following API were renamed:
-  `queue_plan_add` renamed to `queue_item_add`,
- …
> Renaming of API to refer plan queue items as 'items' instead  of 'plans'.

- .github/workflows/docs_publish.yml
Follow up PR that fixes the name of `publish_branch`. Original PR: https://github.com/bluesky/bluesky-queueserver/pull/101
> CI: updated configuration

- .github/workflows/docs.yml
- .github/workflows/docs_publish.yml
- .github/workflows/testing.yml
- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/tests/test_comms.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/server.py
Implemented thread-based API for communicating with RE Manager from 3rd party applications. The QueueServer provided asyncio-based API (class `ZMQCommSendAsync`) used by HTTP Server and CLI tool. The thread-based version of the API (class `ZMQCommSendThreads`) proposed in this PR provides similar functionality for applications that are not running asyncio loop (e.g. PyQT applications).
The API allows to send ZMQ requests to RE Manager in blocking mode or using callbacks. 
Blocking mode:
```
client = ZMQCommSendThreads()
try:
msg = client.send_message(
method="queue_item_add", params={"plan": _plan1, "user":  "Some User", "user_group": "admin"}
)
print(f"Response is received from RE Manager: {msg}")
except CommTimeoutError as ex:
print(f"Communication error occurred: {ex}") 
```
The same …
> Thread-based API for communicating with RE Manager via ZMQ.

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/tests/test_http_server.py
The PR contains fixes for minor inconsistencies in ZMQ API. The PR implements changes suggested in Issue https://github.com/bluesky/bluesky-queueserver/issues/104. Changes are applied to the following API:
**queue_get**
- Add return parameters `success` and `msg` (for consistency with the rest of API). 
- Rename `running_plan` to `running_item` (missed whan plan queue items were renamed from 'plans' to 'items').
**history_get**
- Add return parameters `success` and `msg` (for consistency with the rest of API). 
**history_clear**
- return parameter `msg` should be `""` if request is processed successfully.
**queue_item_get**, **queue_item_remove**, **queue_item_move**
- return parameter `plan` should be renamed to `item.
**queue_clear**
- return parameter `msg` should be `""` if request is …
> Fix for minor inconsistencies in ZMQ API

- CONTRIBUTING.rst
Hey please consider this somewhat of a tentative PR, I'm not sure if the documentation as is would have worked for some setups? But I found when I tried to run it that the slash was needed as I guess it was meant to be a path, so I assumed this was a typo?
**Also I gained a bit of experience in trying to run the unit tests** on my local machine that I felt wasn't really documented in the current README or CONTRIBUTING docs. **I'm happy to add those steps to the documentation** provided I didn't miss it already being documented or mentioned somewhere else already?
It wouldn't be much, just the steps to execute and the prerequisites (**like having a running redis server when running the tests, and http server**)
Regarding my experience having to manually start the redis service and http …
> DOC: correct typo in flake8 command

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/test_http_server.py
Change the method name for `ping` ZMQ API from `""` (empty string) to `ping`. The change is not expected to break any existing code. `ping` request can be sent via HTTP server using both `/` and `/ping` API.
Contains all commits from PR https://github.com/bluesky/bluesky-queueserver/pull/108
Addresses issue https://github.com/bluesky/bluesky-queueserver/issues/107
> Rename ZMQ API 'ping' API

- README.rst
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/test_http_server.py
Implementation of REST API (`/permissions/reload`) and CLI (`qserver permissions reload`) support for `permissions_reload` ZMQ API.
Contains all commits from PR https://github.com/bluesky/bluesky-queueserver/pull/110
Addresses the issue https://github.com/bluesky/bluesky-queueserver/issues/112
> REST API and CLI support for 'permissions_reload' API

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/_common.py
- bluesky_queueserver/manager/tests/test_fixtures.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
Support for additional `meta` key in the plan parameters. `meta` key may reference to a dictionary of metadata:
```
plan = {"name": "scan", "args": [["det1", "det2"], "motor", -1, 1, 10], "meta": {"value1": 1, "value2": 2}}
```
Or a list of dictionaries:
```
plan = {"name": "scan", "args": [["det1", "det2"], "motor", -1, 1, 10], 
"meta": [{"value1": 1, "value2": 2}, {"value3": 3, "value4": 4}]}
```
If `meta` is a dictionary, it is passed to Run Engine without change. If `meta` is a list, the elements of the list (dictionaries) are merged before passing to Run Engine so that the values of the top level keys for elements with lower index overwrite the values of the same keys in elements with higher index. For example,
```
"meta": [{"value1": 1}, {"value2": 2}]  yields {"value1": 1, …
```
> Adding plans to the queue: metadata

- docs/source/re_manager_api.rst
Fixed a number of typos in documentation. Includes changes from review of PR https://github.com/bluesky/bluesky-queueserver/pull/108 
The PR contains commits from PRs https://github.com/bluesky/bluesky-queueserver/pull/116, https://github.com/bluesky/bluesky-queueserver/pull/113 and https://github.com/bluesky/bluesky-queueserver/pull/110
> DOC: fixed typos in documentation.

- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/_common.py
- bluesky_queueserver/manager/tests/test_fixtures.py
- bluesky_queueserver/manager/tests/test_manager_options.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
The PR partially addresses the issue https://github.com/bluesky/bluesky-queueserver/issues/114:
- Additional CLI option `--startup-profile` for `start-re-manager` is added, which allows to specify the name of IPython profile that contains the collection of startup files. The option works the same as `--startup-dir`, except that it does not require the user to specify path to the directory that contains startup files, but constructs the path based on the settings of IPython and provided profile name. The files are expected to be located at `<IPython_config_dir>/profile_<profile_name>/startup`. The parameter `--startup-profile` can not be used if IPython is not installed.
- The parameters `--startup-dir` and `--startup-profile` are mutually exclusive. The manager will fail to start if both …
> Loading of startup files based on IPython profile name.

- README.rst
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/_common.py
- bluesky_queueserver/manager/tests/test_manager_options.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/server/tests/test_http_server.py
- setup.py
The PR addresses the remaining requirements from issue https://github.com/bluesky/bluesky-queueserver/issues.
Changes:
- Additional parameters for `start-re-manager`: `--startup-module` followed by name of the module (on the module search path) and `--startup-script` followed by full path to the script to load.
- Scripts with local imports are not supported. The option to load scripts with local imports is implemented and tested, but disabled.
- CLI parameters for `qserver_list_of_plans_and_devices` are modified to support loading startup data from a script or a module.
- Unit tests covering new functionality are implemented.
> Populating worker namespace by loading a scripts or importing a module

- README.rst
- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/test_comms.py
Changed default port number for ZMQ control connection from 5555 (common ZMQ port) to 60615.
> Changed the default ZMQ port for control connection

- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/_common.py
- bluesky_queueserver/manager/tests/test_manager_options.py
- bluesky_queueserver/manager/worker.py
A built-in option to subscribe Run Engine to `bluesky.callbacks.zmq.Publisher` is added. The address of 0MQ proxy is passed with `start-re-manager` CLI parameter `--zmq-data-proxy-addr`. Identically to subscription to Kafka, the option works for Run Engine created by RE Manager and in the startup script (`start-re-manager` called with `--keep-re`). If the parameter `--zmq-data-proxy-addr` is not used, RE is not subscribed to the Publisher callback.
> Subscribing RE to 0MQ Publisher

- docs/source/re_manager_api.rst
Minor documentation fix: the required parameters `user_group` and `user` are missing from documentation for `queue_item_add` 0MQ API.
> DOC: add 'user' and 'user_group' as required parameters for 'queue_item_add' API

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/_common.py
- bluesky_queueserver/manager/tests/test_manager_options.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_start_manager.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/profile_collection_sim/existing_plans_and_devices.yaml
Changes:
- new CLI parameter (`--redis-addr`) for passing Redis host name to RE Manager (`start-re-manager`). The parameter allows to pass Redis host name (e.g. `localhost` or `127.0.0.1`) or host name with Redis port number (e.g. `localhost:6379` or `127.0.0.1:6379`). If port is not specified, then the default Redis port (`6379`) is used.
- Minor code refactoring: the function `parse_plan` renamed to `prepare_plan`.
- A new parameter (`is_movable`) is added to device parameters in the list of available devices. The parameter is determined using `bluesky.utils.is_movable`.
- Fixed the issue that surfaced after upgrade to `xarray 0.17.0`. The fix includes renaming private attributes `RunEngineWorker._config` and `RunEngineManager._config` to `._config_dict`. Attribute `._config` overrides …
> New CLI parameter: '--redis-addr' ('start-re-manager')

- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/profile_tools.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_tools.py
- bluesky_queueserver/manager/worker.py
Implementation of API function `is_re_worker_active()` for using in startup scripts or modules. The API function returns boolean value that tells if the script is executed in RE Worker environment. One potential use of the API is to disable interactive features in a script (such as manual input) when the script is executed autonomously in RE Worker environment:
```
from bluesky_queueserver.manager.profile_tools import is_re_worker_active
...
if is_re_worker_active():
(code without interactive features, e.g. reading data from a file)
else:
(code with interactive features, e.g. manual data input)
...
```
`is_re_worker_active()` may be used in any code executed by the RE Worker process including the modules imported by startup scripts. 
The `is_re_worker_active()` function checking if an …
> API for detecting if the script is executed in RE Worker environment.

- README.rst
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/profile_tools.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/profile_collection_sim/user_group_permissions.yaml
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/conftest.py
- bluesky_queueserver/server/tests/test_http_server.py
- docs/source/re_manager_api.rst
New API to update/replace existing item in the queue. The updated/replaced item is addressed by item UID. If item is not found then request fails. The operations of updating and replacing items is almost identical, except that an item UID is not changed while the item is updated and replaced with the new randomly generated item UID when the item is replaced. The 'update' operation is intended for insignificant changes in item parameters (e.g. editing the existing plan) and 'replace' operation for replacing items with different items.
- 0MQ API: **queue_item_update** accepts parameters that include the modified item (`plan` or `instruction`) with `item_uid` set to item UID of the item to be updated, `user` and `user_group`, and optional boolean parameter `replace`. If only the item …
> New API to update/replace queue item

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_monitoring.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/test_start_manager.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/server/server.py
The set of CLI parameters was added to `start-re-manager` that allow to modify verbosity of logging output. Currently logging can only be sent to stdout/stderr. By default, RE Manager will display log messages starting from `loglevel=INFO`. The log includes warnings, errors, brief messages with information about the state of the manager and worker processes and executed steps. This behavior may be modified by calling `start-re-manager` with the following mutually exclusive parameters:
- `--verbose` prints all logging messages including `DEBUG` messages. In addition to short messages indicating the executed steps, the output will display contents of all received/send messages, submitted plans etc. Verbose output may be useful for debugging purposes, but may slow down the system if the plan …
> CLI arguments for 'start-re-manager' to set logging verbosity

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_fixtures.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- docs/source/re_manager_api.rst
Extension of functionality of RE Manager includes two new status fields returned by `status` request:
- `plan_queue_uid` - plan queue UID, which is changed each time plan queue is updated.
- `plan_history_uid` - plan history UID, which is changed each time plan queue is updated. 
Current value of `plan_queue_uid` is also returned as part of response to `queue_get` request and current value of `plan_history_uid` is returned as part of response to `history_get` request. The status fields may be used to detect changes in the queue and history by periodically requesting RE Manager status and download data from the server only when the queue or the history changes. This may allow to prevent unnecessary downloads and reduce network traffic. The changes are reflected in documentation for …
> New RE Manager status fields: 'plan_queue_uid' and 'plan_history_uid'

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/test_http_server_func_scope.py
- docs/source/re_manager_api.rst
Implementation of `queue_item_add_batch` 0MQ API. Each item in the batch is validated and the the batch is added to the queue only if each item successfully passes validation. The returned item list contains `success` status for and error message for each item. The returned information is sufficient for generating detailed reports that could be displayed to the user.
The handler for `/queue/upload/spreadsheet` is modified to use `queue_item_add_batch`. The return parameter `result` was renamed to `item_list` (I don't think the parameter was used in any code yet).
The API documentation is added to 0MQ API section.
The PR addresses the issue https://github.com/bluesky/bluesky-queueserver/issues/139
> 0MQ API for adding a batch of items to the back of the queue ('queue_item_add_batch')

- bluesky_queueserver/server/conversions.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/_common.py
- bluesky_queueserver/server/tests/test_conversions.py
- bluesky_queueserver/server/tests/test_http_server_func_scope.py
Implementation for default (built-in) function for converting a spreadsheet to a list of plans. The plan parameters are expected to be represented as a table in straightforward way following guidelines. Users that require support for more sophisticated or custom spreadsheets may write their own processing function. The function supports `.xlsx` (Excel) and `.csv` files. Only the first sheet of an Excel workbook will be loaded.
The screenshot of an Excel spreadsheet with sample simulated plans:
```
Guidelines:
- The first row contains column names. The names of columns 1 and 2 can be
arbitrary, but should be kept informative. It is recommended to name column 2 as
'args'. The remaining column names should strictly match names of plan kwargs.
- Each of the remaining rows contains parameters …
```
> Implementation for a default spreadsheet processing function

- README.rst
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_fixtures.py
- bluesky_queueserver/manager/tests/test_manager_options.py
- bluesky_queueserver/manager/tests/test_profile_tools.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/conversions.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/_common.py
- bluesky_queueserver/server/tests/conftest.py
- bluesky_queueserver/server/tests/http_custom_proc_functions.py
- bluesky_queueserver/server/tests/test_conversions.py
- bluesky_queueserver/server/tests/test_http_server.py
- bluesky_queueserver/server/tests/test_http_server_func_scope.py
- docs/source/re_manager_api.rst
Modification to 0MQ API functions to improve consistency of names and representation API parameters. See issue https://github.com/bluesky/bluesky-queueserver/issues/143 for details.
The PR contains changes that will break existing code:
- `queue_get` returns the list of items in the queue as parameter `items` instead of  `queue`;
- `history_get` returns the list of items in history as parameter `items` instead of  `history`;
- `queue_item_add` and `queue_item_update` accept items of all types as parameter `item` (used to be parameter name `plan` and `instruction` depending on the item type;
- item parameters accepted by functions `queue_item_add`, `queue_item_update` and `queue_item_add_batch` now include required parameter `item_type` which can take values `plan` or `instruction` …
> Consistent representation of items in 0MQ API

- README.rst
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/_common.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/test_http_server_func_scope.py
Implemented an option to pass custom RE Manager 0MQ address to HTTP Server by setting the environment variable `QSERVER_ZMQ_ADDRESS`, e.g.
```
export QSERVER_ZMQ_ADDRESS='tcp://localhost:60615'
```
Unit tests for operation of RE Manager and HTTP Server using 0MQ address different from default.
Additional changes:
- Changed log level for message acknowledging request of RE Manager status to `debug` (to clear the log).
Addresses the issue https://github.com/bluesky/bluesky-queueserver/issues/148
> Option to set custom 0MQ address for communication between HTTP Server and RE Manager

- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/profile_collection_sim/99-custom.py
- bluesky_queueserver/profile_collection_sim/existing_plans_and_devices.yaml
In the original code the list of devices was generated by picking objects that are subclasses of `ophyd.Device`. In this PR, the criteria for selection of devices is changed to include all types inherited from `OphydObject`. The list of devices will include all objects that are subclassed from `ophyd.Device` and `ophyd.Signal`. Any objects of custom types inherited from `OphydObject` will be also included.
> Include all items of types inherited from `OphydObject` into the list of devices

- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
Change the queue behavior so that new UID is generated for the item before it is pushed into the queue in case a plan is stopped or failed. This prevents multiple execution attempts of a plan with the same item UID and guarantees that the plan history contains items with unique UIDs. 
Additional changes:
- Filtering of plan parameters: all added queue items are passed through the filter that removes all item parameters that are not included in the list. The purpose of the filtering is to make sure that the items do not contain unsupported parameters and to remove 'result' parameter that may be present in the items that are copied from history or were pushed back into the queue after they were stopped or if their execution failed. All operations on the items except `move` operations within …
> Generate new item UIDs for failed and stopped items that are pushed back into the plan queue

- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
Modifications to the code that controls the item queue so that all operations except moving items within the queue involve the step of filtering of parameters. The filtering involves removing of all parameters that are not in the list of allowed parameters. The list of allowed parameters is an attribute of the `PlanQueueOperations._allowed_item_parameters`:
```
self._allowed_item_parameters = (
"item_uid",
"item_type",
"name",
"args",
"kwargs",
"meta",
"user",
"user_group",
)
```
The function `PlanQueueOperations._add_item_to_queue()` has additional optional parameter `filter_parameters` with default value of `True`. If the function is called with `filter_parameters=False`, the parameter filtering is skipped. Currently it is not expected that the option of skipping the parameter filtering …
> ENH: filtering of parameters during operations with queue items

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/test_http_server.py
- docs/source/re_manager_api.rst
Implementation of 0MQ API `queue_item_remove_batch` and REST API `/queue/item/remove/batch`. The new API are important for supporting 'atomic' batch operations on the queue.
Addresses issue https://github.com/bluesky/bluesky-queueserver/issues/157
> API extension: new 0MQ API 'queue_item_remove_batch'

- bluesky_queueserver/manager/_abc.py
- bluesky_queueserver/manager/_protocols.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/profile_collection_sim/99-custom.py
- bluesky_queueserver/profile_collection_sim/existing_plans_and_devices.yaml
- requirements.txt
Changes include the updated method identification of devices in the worker namespace. Old approach required the devices to be inherited from `ophyd.ophydobj.OphydObject`. The new approach is using `bluesky.abc` to check if the object is `abc.Readable` or `abc.Flyable`.
The PR requires https://github.com/bluesky/bluesky/pull/1446, which must be merged before this PR is merged. Unit tests are expected to pass then. 
Addresses issue https://github.com/bluesky/bluesky-queueserver/issues/162
> ENH: use 'bluesky.abc' to identify devices in the workspace

- bluesky_queueserver/__init__.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- docs/source/interacting_with_qs.rst
Implementation of the function `format_text_descriptions` which returns complete formatted text descriptions for plans and plan parameters. The original code for the function was moved from `bluesky-widgets` projects. The code was also modified to reflect recent changes in schema used to represent plan parameter description. 
The function is intended for use in client GUI applications. It can be imported from `bluesky_queueserver` package:
```
from bluesky_queueserver import format_text_descriptions
```
Addresses the issue https://github.com/bluesky/bluesky-queueserver/issues/179.
> Function for formatting plan and plan parameter descriptions

- bluesky_queueserver/__init__.py
- bluesky_queueserver/manager/profile_tools.py
- docs/source/startup_code.rst
Changes in this PR:
- add imports of `is_re_worker_active()`, `set_re_worker_active()` and `clear_re_worker_active()` API to `bluesky_queueserver/__init__.py` so that they could be imported from `bluesky_queueserver` module.
- documentation on `is_re_worker_active()`, `set_re_worker_active()` and `clear_re_worker_active()` API
> Import `is/set/clear_re_worker_active()` API from `bluesky_queueserver` module.

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/server.py
- bluesky_queueserver/server/tests/conftest.py
- bluesky_queueserver/server/tests/test_http_server.py
- docs/source/re_manager_api.rst
Implementation for the new API method: `queue_item_execute`. The method immediately starts execution of a plan or instruction. If execution of the item can not be started, the request fails. Meaningful error message is returned to the client that sent the request.
Code changes:
- Implementation of 0MQ API method `queue_item_execute`.
- Implementation of REST API method `/queue/item/execute`.
- Access to the new API method using `qserver` CLI tool (`execute plan` and `execute instruction` options).
- Unit tests for the new 0MQ and REST API and `qserver` options.
- Documentation for `queue_item_execute` 0MQ API.
The PR fully addresses the issue https://github.com/bluesky/bluesky-queueserver/issues/167
> New 0MQ API: `queue_item_execute`

- bluesky_queueserver/manager/plan_queue_ops.py
Hi Dmitri, I set up the queueserver on a new machine and forgot to provide dependencies like redis so I thought this might be a small help if another person gets stuck on that, what do you think?
> ENH: show helpful error message if no redis server available

- README.rst
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_manager.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/server/tests/test_http_server.py
- requirements.txt
Contributions:
- implemented the code that checks if 0MQ API requests contain unsupported parameters. Unsupported parameters (parameter names) in API calls may indicate the error in the client code. If unsupported parameters are found the API request is rejected with appropriate error message. The change is not supposed to affect client code unless it is using extra 'unsupported' parameters in API calls.
- added examples for `queue_item_execute` API in README.rst.
> Check API requests for unsupported parameters

- bluesky_queueserver/manager/annotation_decorator.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_annotation_decorator.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/profile_collection_sim/99-custom.py
- docs/source/plan_annotation.rst
Minor improvement to `parameter_annotation_decorator`.
Use Python expressions to define values of `default`, `min`, `max` and `step`. The original decision to use string representation of values does not provide any advantages over Python expressions. The values of `min`, `max` and `step` could be of `int` and `float` type (used only for numerical values) and `default` may be of any type that could be converted to string (see https://blueskyproject.io/bluesky-queueserver/plan_annotation.html#supported-types).
Strings are still used to represent annotations in the decorator, because the expressions may contain custom enum types that do not exist in Python code.
To this point there are no known users of `parameter_annotation_decorator`, so the change is unlikely to break any code.
> Annotation Decorator: Use Python expressions for 'default', 'min', 'max' and 'step'

- docs/source/release_history.rst
- requirements-dev.txt
Update to `sphinx_rtd_theme==1.0.0` resulted in corrupt documents, so it had to be pinned to previous stable version 0.5.2.
> CI: pinned 'sphinx_rtd_theme==0.5.2'

- docs/source/_static/theme_overrides.css
- docs/source/conf.py
- requirements-dev.txt
Old method for providing a list of additional CSS files obviously does not work anymore. Fix `conf.py` file to make it compatible with `sphinx_rtd_theme` v1.0.0. Unpin `sphinx_rtd_theme`.
> Fix issue with `sphinx_rtd_theme` v1.0.0

- bluesky_queueserver/manager/logging_setup.py
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/output_streaming.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- docs/source/re_manager_api.rst
Changes that extend functionality of the queue server:
- Extend the set of states of worker environment. Currently used states include `initializing`, `idle`, `executing_plan`, `executing_task`, `closing`, `closed`.
- Return the state of worker environment as a `worker_environment_state` status parameter of RE Manager
Maintenance (most of the PR):
- Modified code that is used to start and stop the manager during unit tests. The manager is now started in `--verbose` mode, `stdout` and `stderr` are captured and displayed for failing tests (useful for finding issues). The code for stopping the manager is now more robust and successfully stops the manager in most failing cases (the test is still registered as failed, but it is much less likely that consecutive tests using RE Manager will fail …
> Return 'worker_environment_state' as one of RE status parameters

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/task_results.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_task_results.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/profile_collection_sim/existing_plans_and_devices.yaml
- docs/source/re_manager_api.rst
Implementation of `script_upload` 0MQ API, which uploads and executes a script in RE Worker namespace. The API can be used to dynamically add plans to the namespace. The new plans appear in the list of allowed plans for all user groups with appropriate permissions. The PR also includes implementation for related simple API: `task_load_result` loads information on the running task or the result of a completed  task (scripts are executed as tasks in separate threads), `plans_existing` `devices_existing` load the lists of existing plans and devices (work similarly to `plans_allowed` and `devices_allowed` API, useful for testing).
The PR include documentation on the new API and status fields. CLI access to the new API will be implemented in one of the following PRs.
The API is required to …
> Implementation of 'script_upload' 0MQ API

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/profile_collection_sim/99-custom.py
- bluesky_queueserver/profile_collection_sim/user_group_permissions.yaml
- docs/source/re_manager_api.rst
- requirements-dev.txt
Implementation of a 0MQ API that starts execution of a user-defined function in RE Worker namespace. The function must be defined in RE Worker namespace, e.g. in startup script. The function can be executed in foreground or background. Support for new options for user group permissions (``allowed_functions`` and ``forbidden_functions``) are implemented to filter the names of the functions allowed for users from different group. Handling of user permissions is updated to make all entries of `user_group_permissions.yaml` optional. Changes to user group permissions handling are not expected to change existing behavior. A new field (`worker_background_tasks`) which indicates the number of background tasks running in RE Worker environment is added to status information returned by RE Manager …
> New 0MQ API: 'execute_function'

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/profile_collection_sim/user_group_permissions.yaml
- docs/source/cli_tools.rst
- docs/source/re_manager_api.rst
Implemented CLI support for new 0MQ API:
- `qserver script upload` (`script_upload` API);
- `qserver function execute` (`function_execute` API);
- `qserver task result get` (`task_result_get` API);
- `qserver existing devices` (`devices_existing` API);
- `qserver existing plans` (`plans_existing` API).
Renamed `task_load_result` API to `task_result_get`. The latter name is more consistent with other API names (the respective name for REST API is going to be `/task/result/get`. The API was implemented very recently, so no user code using this API is expected to exist.
Several previous PRs introduced new 0MQ API, but contained no CLI implementation. 
- CLI implementation for the new 0MQ API:  `qserver script upload` (`script_upload` API), `qserver function execute` (`function_execute` API), …
> CLI support for new API

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_start_manager.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- docs/source/cli_tools.rst
- docs/source/features_and_config.rst
- docs/source/re_manager_api.rst
Implementation for new 0MQ API: `permissions_set` (upload dictionary with user group permissions) and `permissions_get` (download dictionary with user group permissions). Additional `reload_permissions` parameter for `permissions_reload` API, which controls if permissions are to be reloaded from disk. Improved management of user group permissions: the latest version of permissions is always stored in Redis, new `--user-group-permissions-reload` parameter of `start-re-manager` controls when permissions could be reloaded (options are `NEVER`, `ON_REQUEST` and `ON_STARTUP`).
The implemented features are not expected to change the default behavior of RE Manager or break any code using 0MQ API.
The new features are implemented as part of development of new features to support more complex …
> New 0MQ API: 'permissions_set' and 'permissions_get'

- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- requirements.txt
The PR contains several small changes to provide compatibility with ``aioredis`` v2. The code still works with ``aioredis`` v1. Switching to v2 also required refactoring of unit tests for plan queue operations that accounts for the rest of the changes.
Resolves the issue https://github.com/bluesky/bluesky-queueserver/issues/185
- Implemented changes to make Queue Server compatible with ``aioredis`` v2.
> ENH: compatibility with 'aioredis v2'

- bluesky_queueserver/manager/annotation_decorator.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/profile_collection_sim/user_group_permissions.yaml
- docs/source/conf.py
- docs/source/features_and_config.rst
- docs/source/plan_annotation.rst
Support for subdevice names in `user_group_permissions.yaml`. Changes in this PR may require replacing or editing the existing `user_group_permissions.yaml`.
The PR provides support for patterns that allow filtering (including, excluding) device and subdevice names while generating lists of allowed plans and devices. The syntax for the patterns is identical to syntax for patterns in the lists of plans and devices in `parameter_annotation_decorator` (introduced in PR https://github.com/bluesky/bluesky-queueserver/pull/209). In the older versions, user group permissions were defined using regular expressions, but now they may include explicitly listed names and patterns based on regular expressions. The file `user_group_permissions.yaml` used in projects may need to be updated to work with …
> Suport for subdevice names in `user_group_permissions.yaml`

- docs/source/re_manager_api.rst
- docs/source/startup_code.rst
- docs/source/tutorial.rst
The PR includes a few tutorials that are demonstrating basic features of Queue Server. I am planning to write another set of 'advanced' tutorials to demonstrate less obvious features.
The best way to read the tutorials is to built HTML by running ` make -C docs/ html`.
**For reviewers.** It is best to split the comments into two categories: comments on how to improve the tutorials in this PR so that they could be merged and published and suggestions on what topics to cover in additional basic tutorials and documentation and how to expand the existing outline.
> Basic tutorials (Documentation)

- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/profile_collection_sim/99-custom.py
After the PR https://github.com/bluesky/bluesky-queueserver/pull/209, RE Manager allows to pass subdevice names as parameters to plan. The current parameter validation code requires that the full tree of subdevices for each existing is created after startup files are loaded. Testing at the beamline exposed issues with this procedure. Particularly, AD subdevices are instantiated only when they are accessed and they attempt to access PVs in the process. In practice many of the PVs do not exist, resulting in exceptions being raised and environment failing to open. This PR contains fix for the issue. Now the subdevices devices that fail to instantiate are ignored and not included in the tree. In order to minimize loading time, all subdevices of a device (or subdevice) are ignored if only one …
> ENH: catch exceptions for components that are not accessible

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- docs/source/re_manager_api.rst
Minor fixes in documentation. Extra tests for `status` API. Implementation of the new API `task_status`, which returns the status of one or more tasks executed by the server. The API is needed for completeness.
- New `task_status` API. The API may be called for a single task from CLI as `qserver task status <task-uid>`.
- `status` API is now returning Queue Server version number as part of `msg`, e.g. `"RE Manager v0.0.10"`.
Unit tests were implemented.
> New 0MQ API ('task_status')

- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
Changes to how negative indices passed to `queue_item_add` API are handled. Previously, `pos=-1` would add the new element to the position previous to last. Now the new element will be added to the back of the queue if `pos=-1`, to the position previous to last if `pos=-2` etc. Now `pos` specifies the position of the added element in cases of both positive and negative indices. The changes will not break existing code unless negative indices are used to add new items in the queue.
- Fixed handling of negative item indices by `queue_item_add` API (`pos=-1` now adds an item to the back of the queue).
> Fix handling of negative indices by 'queue_item_add' API

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_profile_tools.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- docs/source/cli_tools.rst
- docs/source/re_manager_api.rst
- Renamed parameters of `permissions_reload` API. The parameters control if permissions or existing plans and devices are reloaded from disk files (or Redis):  `reload_permissions` is renamed to `restore_permissions`, `reload_plans_devices` is renamed to `restore_plans_devices`.
- Minor fixes to API documentation.
- Renamed parameters of `permissions_reload` API: `reload_permissions` is renamed to `restore_permissions`, `reload_plans_devices` is renamed to `restore_plans_devices`.
Unit tests are modified to work with updated parameter names.
> Renamed parameters of 'permissions_reload' API. 

- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
Implemented validation of 0MQ requests and orderly processing of invalid requests. 
Queue Server may accidentally receive requests that are not JSON or contain invalid JSON. Those requests must be properly processed and should not influence operation of the server. The PR implements basic processing for such requests. If invalid request is received, the server responds by sending ``success: False`` and error message to the sender. The requests do not influence operation of the server.
It was reported that Queue Server behaves incorrectly if the respective 0MQ port is probed by the security scanner. The changes implemented in this PR may fix the issue. Otherwise the issue will need to be further investigated.
- Implemented proper handling of non-JSON or invalid JSON requests.
Unit tests …
> Processing of invalid 0MQ requests

- bluesky_queueserver/manager/output_streaming.py
- bluesky_queueserver/profile_collection_sim/99-custom.py
- bluesky_queueserver/profile_collection_sim/existing_plans_and_devices.yaml
Fix the mechanism of capturing console output with special sequences in Python 3.8, 3.9. It was discovered that `colorama` package replaces `sys.stdout` and removes some special sequences from captured output. Progress bars were not displayed by RE Manager or remote monitor as a result. 
Additional plan `plan_test_progress_bars()` was added to the simulated profile collection. The plan displays multiple dynamically changing progress bars and could be used to verify if progress bars are correctly displayed by the Queue Server or remote monitor.
- Console output containing dynamically changing progress bars is now properly captured and displayed under Python 3.8, 3.9.
> Fixed capture of console output with special sequences in Python 3.8, 3.9

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- docs/source/re_manager_api.rst
Revised the set of `exit_status` values included in plan history. The original set of `exit_status` values was excessive, incomplete and not systematic. Now exit status may take values: `completed`, `stopped` (successful completion) and `failed`, `aborted`, `halted` (failed). Additionally `exit_status` may take the value `unknown` in case the status completion data is lost, for example if during startup or restart RE Manager detects a plan that was set for execution, but not completed and no information on the results of execution could be loaded from RE Worker environment. This is should not happen often in practice. 
The `stopped` plans are considered successful and no longer pushed back in the queue. The `stopped` plans are inserted in the back of the queue in LOOP mode.
Additionally, …
> Revisit the code for reporting 'exit_status' and error message for plans

- .github/PULL_REQUEST_TEMPLATE.md
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- docs/source/re_manager_api.rst
Enable support for `environment_destroy` API in `creating_environment` state of RE Manager. This allows to remotely destroy environment in case execution of the startup script gets stuck in the infinite wait or loop. The changes are not expected to affect execution of the existing code.
The operation of destroying the RE Worker environment is intended for remote recovery of the server if the environment becomes unresponsive due to crashing or freezing of the user code. This is possible on the stages of opening the environment (execution of startup scripts) and while running a plan or a task (existing environment). Originally requests to destroy the environment were supported only if the environment existed (loading of startup scripts was completed). The requests were rejected if the …
> Support for 'environment_destroy' API in 'creating_environment' state of RE Manager

- bluesky_queueserver/__init__.py
- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_comms.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
Make API for generation of encryption key pairs (`generate_zmq_keys`, `generate_zmq_public_key`, `validate_zmq_key`) importable from `bluesky_queueserver`. 
The changes also include minor fixes to docstrings and minor refactoring of `zmq_secure_request` function used in unit tests.
- API functions `generate_zmq_keys`, `generate_zmq_public_key`, `validate_zmq_key` can now be imported directly from `bluesky_queueserver`.
> Make API for generation of encryption keys importable directly from the 'bluesky_queueserver'

- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
The changes in this PR were implemented to minimize modifications of startup scripts and workflow of SRX beamline:
- The global variable `__file__` is set to the path of the original script, not the temporary file with the patched version of the script. The patching is performed only for IPython-style startup scripts.
- Queue Server is no longer automatically search for components (subdevices) of Area Detectors (subclasses of `ADBase`). Scanning for components of an Area Detector involves instantiation of hundreds of unnecessary classes and attempts to communicate to non-existing PVs and may take multiple minutes. Components of Area Detectors are very unlikely to be used as plan parameters so the change is not expected to influence functionality. Means to override the default behavior, …
> Patch `__file__` in startup scripts. Do not automatically look for subdevices of Area Detectors. 

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- docs/source/conf.py
- docs/source/re_manager_api.rst
Minor improvement of the code for loading IPython-style startup code. Since in the new version of loading code implemented in https://github.com/bluesky/bluesky-queueserver/pull/239 the script is patched without adding new lines by inserting patches in the existing lines, the patch should be added to the line before the first `#` if the line contains comments (otherwise the patch is added to the comment).
Minor change in API: if a plan or a task fail, the full traceback is returned as a separate parameter. It used to be part of the error message (`"msg"`) for the plan results (in plan history) and return value (`"return_value"`) for the tasks (returned by `task_result` API).
- Minor change in representation of plan execution results in items of the plan history. If plan execution fails, …
> Patching IPython code with comments

- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
This PR include the following changes:
- Fixed management of failures in RE Worker that happen while preparing to start a plan, e.g. preparing plan parameters. Due to a bug (typo), if exception was raised during at stage the plan was not executed, but instead labeled as successful and RE Manager would stay in `executing_plan` state. Now the run engine executes a short plan that reraises the exception that occurred during plan preparation and the error is processed and reported using the same mechanisms as errors that happen during plan execution.
- Fixed a bug that would not allow to pass single character names of devices to plans.
- Improved processing of strings that are passed to plan with parameters that are not annotated (default parameter handling rules). Now the parameter will …
> Bug fixes: management of failure to start plan, handling of strings in unannotated plan parameters

- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/tests/test_comms.py
The PR contains minor fix for the code that controls communication between processes over pipes using JSON RPC. If the receiving process responds to a single request with multiple (probably identical) replies using correct message UID in rapid sequence so that the second reply is received before handling of the first reply is completed, then the existing code raises the exception, which is not retrieved and results in printed message
```
self._fut_comm.set_result(response) 
asyncio.exceptions.InvalidStateError: invalid state
```
In the fixed code the expected message UID is disabled immediately after the valid message is received and the following responses are ignored (considered 'unsolicited messages').
It is not expected that the worker process responds with multiple messages to a …
> Fix for possible issue with communication between processes

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/profile_tools.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- docs/source/re_manager_api.rst
- requirements-dev.txt
New boolean parameter `update-lists` (default value is `True`) for `script_upload` API. The parameter allows to disable update of the lists of existing and allowed plans and devices after execution of the script. The lists need to be updated only if the uploaded script adds or modifies plans and/or devices that exist in namespace, but may be disabled otherwise. Generating the lists after execution of each script may be costly if workflow requires execution of large number of short scripts, e.g. during interactive debugging session.
The API for uploading and executing scripts was initially intended for adding/removing/modifying plans and devices in RE Worker namespace, which requires updating lists of existing and allowed plans and devices. It is also possible to use scripts for other …
> 'script_upload' API: new parameter 'update-lists'

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- docs/source/cli_tools.rst
- docs/source/features_and_config.rst
- docs/source/re_manager_api.rst
- docs/source/tutorial.rst
- setup.py
Implementation of the new API: 
- `lock` - locks RE Manager (the worker environment and/or the queue) with user-provided lock key;
- `unlock` - unlocks RE Manager;
- `lock_info` - loads lock status and optionally validates the lock key. 
The description of implemented functionality:
The detailed description of the API:
Tutorial:
- New `lock`, `unlock` and `lock_info` API. The API are accessible from CLI using `qserver lock` and `qserver unlock` commands.
- `qserver-clear-lock` CLI tool for unlocking RE Manager if the lock key is lost and the emergency lock key is not set or unknown.
Comprehensive unit tests are implemented.
> New API: 'lock', 'unlock', 'lock_info'

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- docs/source/re_manager_api.rst
- docs/source/tutorial.rst
Minor change to `lock`, `lock_info` and `unlock` API: `lock_info_uid` is returned as a separate parameter instead of being part of `lock_info` dictionary. This behavior is more consistent with the existing API (such as `plans_allowed` or `devices_allowed`). The API are new and the change is not expected to break any existing code.
The unit tests and documentation were modified to reflect the API changes.
> 'lock' API: return 'lock_info_uid' as a separate parameter

- bluesky_queueserver/profile_collection_sim/existing_plans_and_devices.yaml
Generate the updated list of plans and devices for the built-in profile collection so that the resp unit tests `test_verify_default_profile_collection` worked with updated Bluesky/Ophyd.
> FIX: generate the new list of plans and devices to fix unit test

- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_fixtures.py
- bluesky_queueserver/manager/tests/test_manager_options.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_tools.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/profile_collection_sim/existing_plans_and_devices.yaml
- bluesky_queueserver/profile_collection_sim/user_group_permissions.yaml
- docs/source/features_and_config.rst
- docs/source/re_manager_api.rst
- docs/source/tutorials.rst
- docs/source/using_queue_server.rst
As the security features of Bluesky HTTP server are being implemented, the name of the default user group `admin` defined in `user_group_permissions.yaml` becomes increasingly misleading, since it implies administrative privileges. In this PR, the group is renamed from `admin` to `primary`. The applications that rely on default user group name (e.g. do not explicitly set user group name when using Bluesky Queue Server API) should rename `admin` group to `primary` group in `user_group_permissions.yaml`.
- Default user group name is changed from `admin` to `primary`. Users of applications that rely on default user group name should change the group name in `user_group_permissions.yaml` file.
> Rename default user group from 'admin' to 'primary'.

- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/conversions.py
- bluesky_queueserver/manager/logging_setup.py
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/output_streaming.py
- bluesky_queueserver/manager/plan_monitoring.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/plan_lists.py
- bluesky_queueserver/manager/tests/test_comms.py
- bluesky_queueserver/manager/tests/test_logging.py
- bluesky_queueserver/manager/tests/test_scenarios.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/profile_collection_sim/user_group_permissions.yaml
Added new `timeout` parameter for `ZMQCommSendThreads.send_message()`, `ZMQCommSendAsync.send_message()` and `zmq_single_request()` functions. The timeout overrides the default timeout ``timeout_recv`` set during instantiation of the respective classes for the particular request. The parameter is useful for implementation of some unit tests.
Some code refactoring to improve efficiency of logging and processing of submitted plans and functions. The changes are not expected to affect functionality of RE Manager.
- New `timeout` parameter for `ZMQCommSendThreads.send_message()`, `ZMQCommSendAsync.send_message()` and `zmq_single_request()` functions. The timeout overrides the default timeout ``timeout_recv`` set during instantiation of the respective classes for the particular request. …
> `timeout` parameter for 0MQ API

- MANIFEST.in
- bluesky_queueserver/manager/config.py
- bluesky_queueserver/manager/config_schemas/config_schema.yml
- bluesky_queueserver/manager/config_schemas/loading.py
- bluesky_queueserver/manager/logging_setup.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/test_config.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- docs/source/cli_tools.rst
- docs/source/index.rst
- docs/source/manager_config.rst
- requirements-dev.txt
Implemented functionality that allows passing parameters to RE Manager as a configuration file. The path may be passed using `--config` CLI parameter or `QSERVER_CONFIG` environment variable. See `RE Manager Configuration` section in the documentation for more details.
RE Manager is not attempting to load configuration unless the path is passed as EV or `--config` parameter and CLI parameters override parameters passed in configuration file, so the changes are not expect to affect existing deployments.
The config files have similar format as config files used for Databroker/Tiled and Bluesky HTTP Server. Example config file (e.g. `config.yml`):
```
network:
zmq_control_addr: tcp://*:60615
zmq_private_key: ${CUSTOM_EV_FOR_PRIVATE_KEY}
zmq_info_addr: tcp://*:60625
zmq_publish_console: true …
```
> Passing parameters using config file (YML)

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- docs/source/cli_tools.rst
- docs/source/re_manager_api.rst
- docs/source/using_queue_server.rst
The PR implements a new `ignore_failures` mode of the queue.
Normal behavior of the manager in case the currently running plan fails is to stop execution of the queue and push the current plan to the beginning of the queue so that it could be restarted after the problem is fixed. In the `ignore_failures` mode, the manager continues with execution of the next plan even if the current plan fails. The queue is still stopped if the current plan is stopped/aborted/halted. The mode may be useful in the system running independent plans and controlled by an autonomous agent, which is responsible for processing execution results.
The queue is still stopped if the manager fails to submit the request to start a plan to the worker, but this is not expected to occur during normal operation.
Requested …
> Implementation of 'ignore_failures' queue mode

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_monitoring.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_plan_monitoring.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/profile_collection_sim/user_group_permissions.yaml
- docs/source/re_manager_api.rst
- docs/source/using_queue_server.rst
Implementation of 'autostart' mode, in which the queue is automatically started once plans are added to the queue or the manager becomes ready to execute plans (e.g. environment is opened). The autostart mode is enabled by calling `queue_autostart` API with the parameter `enable=True` and disabled by calling the same API with `enable=False`. The autostart mode is disabled automatically if the queue is stopped (using `queue_stop` queue instruction or `queue_stop` API) or a running plan was stopped, halted or aborted. The autostart mode is also disabled if the plan fails, unless the `ignore_failures` mode is enabled (see `queue_mode` API). 
Another new feature was implemented after multiple request from beamline staff. In addition to run UUIDs, the worker is now collecting scan ID from …
> Implementation of Queue Autostart Mode

- .github/workflows/docs.yml
- .github/workflows/docs_publish.yml
- bluesky_queueserver/__init__.py
- bluesky_queueserver/manager/config.py
- bluesky_queueserver/manager/config_schemas/config_schema.yml
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/profile_tools.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_config.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_qserver_console.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- docs/source/cli_tools.rst
- docs/source/re_manager_api.rst
- docs/source/startup_code.rst
- docs/source/tutorials.rst
- docs/source/using_queue_server.rst
- requirements.txt
- setup.py
New `qserver-console` endpoint, which downloads connection info for the running from RE Manager and starts Jupyter Console application. New `config_get` API, which returns kernel connection info.
The PR contains documentation on IPython mode and tutorials for 'autostart' feature and IPython mode.
This PR contain additional features required for full support of IPython mode.
- New `config_get` API. Currently returns IPython kernel connect info (`ip_connect_info` key).
- New parameter of `start-re-manager`: `--ipython-kernel-ip` sets IP address of the kernel, the respective config file parameter is `worker/ipython_kernel_ip` and environment variable `QSERVER_IPYTHON_KERNEL_IP`.
- `qserver-console` CLI tool, which downloads kernel connection info and starts Jupyter Console.
- `qserver …
> Implementation of 'qserver-console'

- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/test_ip_kernel_func.py
- docs/source/cli_tools.rst
- docs/source/tutorials.rst
- setup.py
Minor change to functionality of `qserver-console` CLI app. Jupyter Console is now started using `os.execl` (replaces the current process) instead of being started as a subprocess. The `qserver-console` application is loading connection info from RE Manager, creates the connection file and starts Jupyter Console. 
Jupyter Console exhibited some strange behavior when running as a subprocess. For example the Linux terminal had to be reset to continue operation after quitting the console while running a plan. Now the console is running as an individual process.
Added new entry point: `qserver-qtconsole`, which behaves similary to `qserver-console`, but starts Jupyter Qt Console connected to IPython kernel running in the worker process.
The PR also contains small number of tests for basic …
> Run Jupyter Console as a separate process (qserver-console)

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/tests/test_ip_kernel_func.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
Add additional step of 'reserving' IPython kernel before starting a queue, execution of a plan or a task. To 'reserve' the kernel, the manager is sending a request to the worker, and the worker attempts to start execution loop in IPython kernel. If the kernel is busy or the loop fails to start within short period (timeout is 0.2 s), the `reserve_kernel` request fails, which causes the respective operation (e.g. starting the queue) to fail. 'Reservation' must complete before the manager returns operation result to the client, i. e. if the API request to start the queue (`queue_start`) returns `success=True`, it is guaranteed that the IPython kernel is already running the execution loop and ready to execute plans.
New API `manager_test` was added. The API will be used exclusively for unit …
> 'Reserve' IPython kernel before sending plans/tasks to the worker

- .github/workflows/testing.yml
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_comms.py
- bluesky_queueserver/manager/tests/test_ip_kernel_func.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_scenarios.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- docs/source/cli_tools.rst
- docs/source/re_manager_api.rst
- docs/source/tutorials.rst
- docs/source/using_queue_server.rst
New API: `environment_update` and `kernel_interrupt`. CLI interface: `qserver environment update` and `qserver kernel interrupt`.
The new API to cover the gaps in functionality:
- `environment_update` API updates cached objects in the worker environment based on contents of the worker namespace. The API updates cached reference to RE and lists of existing/allowed plans and devices.
- `kernel_interrupt` API sends interrupt request (Ctrl-C) to IPython kernel.
- New API: `environment_open` and `kernel_interrupt`.
- CLI implementation: `qserver environment open` and `kernel_interrupt`.
> New 'environment_update' and 'kernel_interrupt' API

- docs/source/installation.rst
Currently Python 3.7-3.11 are supported. CI tests are run for Python 3.9-3.11. Support for Python 3.7 will be dropped soon.
> Update installation instructions: supported Python versions

- .github/workflows/testing.yml
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
Changes:
- The original server code works with Pydantic V1 and V2. In this PR, the unit tests were modified to work with both versions of Pydantic. Pydantic V2 performs strict type checking and produces different error messages.
- Removed deprecated use of `pkg_resources.resource_filename`. Identical functionality was implemented using `importlib.resources.files`.
> Compatibility with Pydantic v2

- bluesky_queueserver/manager/config.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
Add current username to the name of temporary directory. The directory used to be named `qserver`, now it is named `qserver_<username>`. The directory is created when RE Manager is started in demo mode with IPython kernel and contains the the copy of `profile_collection_sim` placed in `qserver_<username>/IPython/profile_collection_sim` directory. The `IPython` subdirectory also contains standard files created by IPython kernel, including the history. Having the same directory proved to be inconvenient if the Queue Server is started in demo mode by different users on the same machine. 
The temporary directory is used only in the demo mode if IPython kernel option is enabled. The change does not affect production environment. 
- The temporary directory created by RE Manager in demo mode if …
> Add username to temporary directory name (used in demo mode with IPython kernel)

- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- docs/source/plan_annotation.rst
Add new 'default' types for use in plan descriptions: `__READABLE__`, `__MOVABLE__`, `__FLYABLE__` and `__CALLABLE__`. The `__READABLE__`, `__MOVABLE__` and `__FLYABLE__` types are handled by the server identically to the `__DEVICE__` type: the type is treated as `str` for parameter validation, then all the strings passed with the parameter value (elements of a list, values of a dictionary, etc.) are converted to device objects from the list of allowed devices. The strings that do not match device names from the list of allowed devices are passed to the plan as strings (and if those are expected to be device object, the plan fails during execution). 
Proper validation of parameters based of the list of all allowed devices or lists of readable, movable or flyable subsets of the list could …
> Support for in-header annotations of devices and callables

- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- docs/source/plan_annotation.rst
Extend support of types in plan annotation. New supported types:
- typing.Iterable,
- bluesky.protocols.Configurable,
- bluesky.protocols.Triggerable,
- bluesky.protocols.Locatable,
- bluesky.protocols.Stageable,
- bluesky.protocols.Pausable,
- bluesky.protocols.Stoppable,
- bluesky.protocols.Subscribable,
- bluesky.protocols.Checkable,
The implemented functionality is needed to complete https://github.com/bluesky/bluesky/pull/1610
- Extemded support of types in plan annotation. New supported types: `typing.Iterable`, `bluesky.protocols.Configurable`, `bluesky.protocols.Triggerable`, `bluesky.protocols.Locatable`, `bluesky.protocols.Stageable`, `bluesky.protocols.Pausable`, `bluesky.protocols.Stoppable`, `bluesky.protocols.Subscribable`, `bluesky.protocols.Checkable`.
> Support for Additional Types in Plan Header Annotations

- .flake8
- .github/workflows/testing.yml
- .pre-commit-config.yaml
- .test_durations
- bluesky_queueserver/manager/config.py
- bluesky_queueserver/manager/output_streaming.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_fixtures.py
- bluesky_queueserver/manager/tests/test_ip_kernel_func.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/manager/tests/test_scenarios.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- bluesky_queueserver/manager/tests/test_zmq_api.py
- bluesky_queueserver/manager/worker.py
- bluesky_queueserver/profile_collection_sim/99-custom.py
Maintenance PR:
- update pre-commit;
- run the latest Black on the whole codebase;
- update flake8 configuration (ignore inconsistencies with Black);
- fix a number of tests;
- remove `db_catalog` fixture, which was barely used. Modify the tests (only one test) to work without `db_catalog` fixture.
`bluesky` package is pinned to `v1.11.0`.
> Fix for unit tests

- bluesky_queueserver/manager/config.py
- bluesky_queueserver/manager/config_schemas/config_schema.yml
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_config.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_qserver_cli.py
- bluesky_queueserver/manager/tests/test_start_re_manager_cli.py
- docs/source/cli_tools.rst
- docs/source/index.rst
- docs/source/ipython.rst
- docs/source/manager_config.rst
After the code changes in this PR, RE Manager is adding an identical prefix to each Redis key. The default prefix is `qs_default` (the parameter name `plan_queue` becomes `qs_default_plan_queue`, etc.) A custom prefix can be passed using `--redis-name-prefix` CLI parameter or the `redis_name_prefix` parameter in the `network` section of the YML config file. A properly chosen prefix allows to easily distinguish between parameters created by the queue server and other applications using the same Redis server. Two instance of RE Manager using different prefix can share the same Redis server. (It is still recommended that the Redis server is running on the same machine as RE Manager).
RE Manager can still used old names without prefix. Do configure RE Manager to key names without prefix, pass …
> Add custom prefix to Redis keys

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/worker.py
Minor changes to improve efficiency of plan execution:
- Remove fixed 0.1 delay in the execution loop. Now execution of a plan submitted to the worker starts immediately.
- The request to reserve the kernel is sent to the worker only if the worker is using IPython kernel.
The changes are not expected to modify the behavior of the server. All the existing unit tests are expected to work.
> Efficiency improvements

- bluesky_queueserver/manager/comms.py
- bluesky_queueserver/manager/json_rpc.py
- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/common.py
- bluesky_queueserver/manager/tests/test_comms.py
- bluesky_queueserver/manager/tests/test_json_rpc.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_scenarios.py
- bluesky_queueserver/manager/tests/test_start_manager.py
- bluesky_queueserver/manager/worker.py
- requirements.txt
Queue Server is using JSON RPC protocol for communication between the manager process and other processes. In this PR the communication code is modified so that the messages are not encoded as JSON string by the process sending the message and the decoded by the receiving process. Conversion data (e.g. a large array) to and from a JSON string is slow and completely unnecessary for interprocess communication within one application. Instead, the JSON RPC message is sent as a dictionary via `multiprocessing.Pipe`, which automatically pickles the outgoing message and then unpickles it at the receiving end. The change does not affect user-facing API, but is expected to make Queue Server more stable due to shorter  interprocess communication delays.
Other changes: `json-rpc` package is replaced …
> Disable JSON encoding for interprocess communication

- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/profile_collection_sim/00-ophyd.py
- bluesky_queueserver/profile_collection_sim/existing_plans_and_devices.yaml
Switch to use new `is_plan` function from bluesky utils.
Solves #305 . Requires https://github.com/bluesky/bluesky/pull/1780 to be released, and pinned in the `requirements` file.
Remove `is_plan` function, use instead the equivalent from bluesky utils that can handle the decorated functions.
Bluesky builtin plans that use the `@plan` decorator are now correctly identified by queueserver.
> Use is_plan from bluesky utils

- requirements-dev.txt
- requirements.txt
Both pyarrow and pandas were added as package requirements in commit  672f579 as part of PR#301.  Neither of these are imported by this package.  Shift the both of them to `requirements-dev.txt`.
We ran into an installation dependency in https://github.com/prjemian/model_instrument/pull/5#issuecomment-2408085385.  On inspection, this seems not to be a real requirement of this package.
> shift requirements to dev

- bluesky_queueserver/manager/worker.py
- docs/source/conf.py
The second positional argument to RE() is subscriptions to processed for that invocation.  This avoids adding one more layer to the callstack and a possible confusion with plans that do not set their own name being reported as having the `'plan_name'` of `'subs_wrapper'` in the start document.
This caused some confusion at HEX.  The ultimate fix is that plans that generate start documents should insert their own name into the meta-data of the `open_run` plan so that when used from inside of a bigger plan the name is stable.  This change will not fix the ultimate problem, but it will change what the user sees to be the name of the plan they wrote so it will be clearer what is going on and what they have to do to fix it.
Expect all tests to pass after this change and there to be no …
> MNT: pass callbacks directly to _RE.__call__

- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- docs/source/plan_annotation.rst
Add support for `bluesky.protocols.NamedMovable` to resolve https://github.com/bluesky/bluesky-queueserver/issues/310
Queue server handles the protocol identically to `bluesky.protocols.Movable`.
- Support for `bluesky.protocols.NamedMovable` protocol.
Test case is added to unit tests.
> Add support for NamedMovable protocol

- bluesky_queueserver/manager/qserver_cli.py
- bluesky_queueserver/manager/start_manager.py
- bluesky_queueserver/manager/tests/test_manager_options.py
- docs/source/cli_tools.rst
- docs/source/manager_config.rst
Redis database number may be specified as part of Redis address, e.g. `localhost:6379/0` and passed with `network/redis_addr` parameter in the config file or with `--redis-addr` CLI parameter. 
PR contains no code changes. Test case was added to one of the unit tests.
Related issue: https://github.com/bluesky/bluesky-queueserver/issues/316
> Mention Redis database number in documentation

- .github/workflows/testing.yml
- bluesky_queueserver/manager/profile_ops.py
- bluesky_queueserver/manager/tests/test_profile_ops.py
- bluesky_queueserver/profile_collection_sim/existing_plans_and_devices.yaml
- requirements-dev.txt
The PR resolves the issues https://github.com/bluesky/bluesky-queueserver/issues/327 and https://github.com/bluesky/bluesky-queueserver/issues/328.
Now the Queue Server can properly handle children of Ophyd Async devices and include then in the lists of existing and allowed devices. Also, names of the children of the Ophyd Async devices can now be passed as plan parameters and Queue Server properly converts the names (strings) to the device objects from the namespace.
- Support for children of Ophyd Async devices.
Test cases with Ophyd Async devices are added to existing tests.
> Support for components (children) of ophyd-async devices

- bluesky_queueserver/manager/manager.py
- bluesky_queueserver/manager/plan_queue_ops.py
- bluesky_queueserver/manager/tests/test_plan_queue_ops.py
This is intended as a less nuclear alternative to `history_clear`, allowing you to discard some older history while maintaining the newer, potentially more useful, records.
Add a command to trim the history instead of clearing it completely (`history_trim`).
> Add a command to trim the history instead of clearing it completely
